<?php 
$operationKey = Mage::getStoreConfig('snippetsdk/params/operation_id');
$locale = strtolower(substr(Mage::app()->getLocale()->getLocaleCode(), 0, 2));

?>

<div id="lck">
	<div id="loadImg" style="display:table-cell;width:100%;height:100px;background:#fff;text-align:center;"><center>
		<img src="http://stuff.lck.io/assets/loading.gif" style="position:absolute;z-index:999;"></center>
	</div>
	<iframe src="https://www.luckycycle.com/s/<?php echo $operationKey; ?>/<?php echo $locale; ?>?stop=1" width="100%" height="2000" frameborder="0" onload="document.getElementById('loadImg').style.display='none';"></iframe>
</div>

