<?php

// Get data about current order
$orderId = $this->getOrderId();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
Mage::log("OrderId: ".$orderId);
$session = Mage::getSingleton("core/session");
Mage::log("ids:".Mage::getSingleton('core/session')->getData('order_ids'));
$session->setData("multi", 0);

if($orderId){
    $session->setData("orderId", $orderId);
} else {
    // $session->setData("orderId", false);
    // $session->clear();
    // $_orderIds = Mage::getSingleton('core/session')->getData('order_ids');
    // $session->setData("orderIds", $_orderIds);
    // Mage::log("snippets:".$_orderIds);
}

